import './globals.css';
import { ToastContainer } from 'react-toastify';
import QueryProvider from './provider';
import 'react-toastify/dist/ReactToastify.css';
import RecoilRootWrapper from './RecoilRootWrapper';
import Menu from '@/components/layout/Menu';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <RecoilRootWrapper>
            <ToastContainer />
            {children}
            <Menu />
          </RecoilRootWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
