import './globals.css';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import QueryProvider from './provider';
import 'react-toastify/dist/ReactToastify.css';
import RecoilRootWrapper from './RecoilRootWrapper';

import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <RecoilRootWrapper>
            <ToastContainer />
            {children}
          </RecoilRootWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
